version: "3.9"

services:
  database:
    image: "postgres:latest"
    container_name: foreingfinds-api
    restart: always
    ports:
       - "6543:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: foreingfinds-api